name: pix2pixGAN_tf
channels:
  - defaults
dependencies:
  - absl-py=0.15.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - colorama=0.4.6
  - gast=0.4.0
  - google-pasta=0.2.0
  - grpcio=1.64.0
  - h5py=3.1.0
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - ipython=8.18.1
  - joblib=1.4.2
  - keras=2.6.0
  - keras-applications=1.0.8
  - keras-contrib=2.0.8
  - keras-preprocessing=1.1.2
  - matplotlib=3.3.4
  - numpy=1.19.5
  - opencv-python=4.5.3.56
  - pillow=10.3.0
  - protobuf=3.20.3
  - scikit-learn=0.24.2
  - scipy=1.5.4
  - tensorboard=2.16.2
  - tensorflow=2.6.0
  - tensorflow-addons=0.14.0
  - tensorflow-estimator=2.15.0
  - tensorflow-gpu=2.6.0
  - tqdm=4.62.2
  - werkzeug=3.0.3
